source 'https://rubygems.org'

ruby '2.4.1'

gem 'sinatra'
gem 'require_all'
gem 'fast_jsonapi'
gem 'ticketmaster-sdk'
gem 'pry'
gem 'shotgun'
gem 'eventbrite'
gem 'faraday'
gem 'redis'
gem 'hiredis'
group :test do
  gem 'rspec'
  gem 'rack-test'
end
